const fs = require('fs');
const tsPath = 'src/lib/i18n/translations.ts';
let tsContent = fs.readFileSync(tsPath, 'utf8');

const newTranslations = {
  en: `
      newApp: {
        title: "New Application",
        subtitle: "Select your desired academic program.",
        back: "Back to Dashboard",
        programSelection: "Program Selection",
        academicYear: "Academic Year",
        degreeLevel: "Degree Level",
        programSpecialty: "Program / Specialty",
        preferenceOrder: "Preference Order",
        selectYear: "Select Year",
        selectDegree: "Select Degree",
        selectDegreeFirst: "Select a degree first",
        noPrograms: "No programs available for this degree",
        noActivePrograms: "No active programs found for this degree level.",
        selectProgram: "Select Program",
        selectPreference: "Select Preference Order",
        pref1: "1st Preference",
        pref2: "2nd Preference",
        pref3: "3rd Preference",
        submit: "Submit Application",
        submitting: "Submitting...",
        fillAll: "Please fill out all fields before submitting.",
        duplicateApp: "You have already applied for this exact program in this academic year.",
        duplicatePref: "You have already submitted an application for this preference.",
        submitError: "An error occurred while submitting your application. Please try again.",
        successTitle: "Application Submitted!",
        successDesc: "Your application has been successfully created and is now pending review.",
        redirecting: "Redirecting to dashboard...",
        maxLimit: "You have reached the maximum limit of 3 applications. You cannot add more.",
        loadError: "Failed to load application options. Please try again."
      },`,
  tr: `
      newApp: {
        title: "Yeni Başvuru",
        subtitle: "İstediğiniz akademik programı seçin.",
        back: "Panele Dön",
        programSelection: "Program Seçimi",
        academicYear: "Akademik Yıl",
        degreeLevel: "Derece Seviyesi",
        programSpecialty: "Program / Bölüm",
        preferenceOrder: "Tercih Sırası",
        selectYear: "Yıl Seçin",
        selectDegree: "Derece Seçin",
        selectDegreeFirst: "Önce bir derece seçin",
        noPrograms: "Bu derece için uygun program bulunamadı",
        noActivePrograms: "Bu derece seviyesi için aktif program bulunamadı.",
        selectProgram: "Program Seçin",
        selectPreference: "Tercih Sırası Seçin",
        pref1: "1. Tercih",
        pref2: "2. Tercih",
        pref3: "3. Tercih",
        submit: "Başvuruyu Gönder",
        submitting: "Gönderiliyor...",
        fillAll: "Lütfen göndermeden önce tüm alanları doldurun.",
        duplicateApp: "Bu akademik yılda bu programa zaten başvurdunuz.",
        duplicatePref: "Bu tercih sırası için zaten bir başvuru gönderdiniz.",
        submitError: "Başvurunuz gönderilirken bir hata oluştu. Lütfen tekrar deneyin.",
        successTitle: "Başvuru Gönderildi!",
        successDesc: "Başvurunuz başarıyla oluşturuldu ve şu anda inceleme bekliyor.",
        redirecting: "Panele yönlendiriliyor...",
        maxLimit: "Maksimum 3 başvuru sınırına ulaştınız. Daha fazla ekleyemezsiniz.",
        loadError: "Başvuru seçenekleri yüklenirken hata oluştu. Lütfen tekrar deneyin."
      },`,
  ar: `
      newApp: {
        title: "طلب جديد",
        subtitle: "حدد البرنامج الأكاديمي المطلوب.",
        back: "العودة للوحة التحكم",
        programSelection: "اختيار البرنامج",
        academicYear: "العام الدراسي",
        degreeLevel: "المرحلة الدراسية",
        programSpecialty: "البرنامج / التخصص",
        preferenceOrder: "ترتيب الرغبة",
        selectYear: "اختر العام",
        selectDegree: "اختر المرحلة",
        selectDegreeFirst: "اختر المرحلة أولاً",
        noPrograms: "لا توجد برامج متاحة لهذه المرحلة",
        noActivePrograms: "لم يتم العثور على برامج نشطة لمستوى الدرجة هذا.",
        selectProgram: "اختر البرنامج",
        selectPreference: "اختر ترتيب الرغبة",
        pref1: "الرغبة الأولى",
        pref2: "الرغبة الثانية",
        pref3: "الرغبة الثالثة",
        submit: "إرسال الطلب",
        submitting: "جاري الإرسال...",
        fillAll: "يرجى تعبئة جميع الحقول قبل الإرسال.",
        duplicateApp: "لقد تقدمت بالفعل بطلب لهذا البرنامج في هذا العام الدراسي.",
        duplicatePref: "لقد قمت بالفعل بتقديم طلب بهذه الرغبة.",
        submitError: "حدث خطأ أثناء إرسال طلبك. يرجى المحاولة مرة أخرى.",
        successTitle: "تم إرسال الطلب!",
        successDesc: "تم إنشاء طلبك بنجاح وهو الآن قيد المراجعة.",
        redirecting: "جاري التوجيه إلى لوحة التحكم...",
        maxLimit: "لقد وصلت إلى الحد الأقصى البالغ 3 طلبات. لا يمكنك إضافة المزيد.",
        loadError: "فشل في تحميل خيارات الطلب. يرجى المحاولة مرة أخرى."
      },`,
  fr: `
      newApp: {
        title: "Nouvelle Candidature",
        subtitle: "Sélectionnez votre programme académique souhaité.",
        back: "Retour au Tableau de bord",
        programSelection: "Sélection du Programme",
        academicYear: "Année Académique",
        degreeLevel: "Niveau de Diplôme",
        programSpecialty: "Programme / Spécialité",
        preferenceOrder: "Ordre de Préférence",
        selectYear: "Sélectionner l'Année",
        selectDegree: "Sélectionner le Diplôme",
        selectDegreeFirst: "Sélectionnez d'abord un diplôme",
        noPrograms: "Aucun programme disponible pour ce diplôme",
        noActivePrograms: "Aucun programme actif trouvé pour ce niveau de diplôme.",
        selectProgram: "Sélectionner le Programme",
        selectPreference: "Sélectionner l'Ordre de Préférence",
        pref1: "1ère Préférence",
        pref2: "2ème Préférence",
        pref3: "3ème Préférence",
        submit: "Soumettre la Candidature",
        submitting: "Soumission...",
        fillAll: "Veuillez remplir tous les champs avant de soumettre.",
        duplicateApp: "Vous avez déjà postulé pour ce programme exact cette année académique.",
        duplicatePref: "Vous avez déjà soumis une candidature pour cette préférence.",
        submitError: "Une erreur s'est produite lors de la soumission. Veuillez réessayer.",
        successTitle: "Candidature Soumise !",
        successDesc: "Votre candidature a été créée avec succès et est maintenant en attente d'examen.",
        redirecting: "Redirection vers le tableau de bord...",
        maxLimit: "Vous avez atteint la limite maximale de 3 candidatures.",
        loadError: "Échec du chargement des options de candidature. Veuillez réessayer."
      },`,
  ru: `
      newApp: {
        title: "Новая Заявка",
        subtitle: "Выберите желаемую академическую программу.",
        back: "Вернуться на панель",
        programSelection: "Выбор Программы",
        academicYear: "Учебный Год",
        degreeLevel: "Уровень Степени",
        programSpecialty: "Программа / Специальность",
        preferenceOrder: "Порядок Предпочтения",
        selectYear: "Выберите Год",
        selectDegree: "Выберите Степень",
        selectDegreeFirst: "Сначала выберите степень",
        noPrograms: "Для этой степени нет доступных программ",
        noActivePrograms: "Активные программы для этого уровня не найдены.",
        selectProgram: "Выберите Программу",
        selectPreference: "Выберите Порядок Предпочтения",
        pref1: "1-е Предпочтение",
        pref2: "2-е Предпочтение",
        pref3: "3-е Предпочтение",
        submit: "Отправить Заявку",
        submitting: "Отправка...",
        fillAll: "Пожалуйста, заполните все поля перед отправкой.",
        duplicateApp: "Вы уже подавали заявку на эту программу в этом учебном году.",
        duplicatePref: "Вы уже отправили заявку с этим порядком предпочтения.",
        submitError: "При отправке заявки произошла ошибка. Пожалуйста, попробуйте снова.",
        successTitle: "Заявка Отправлена!",
        successDesc: "Ваша заявка успешно создана и находится на рассмотрении.",
        redirecting: "Перенаправление на панель...",
        maxLimit: "Вы достигли максимального лимита в 3 заявки. Вы не можете добавить больше.",
        loadError: "Не удалось загрузить варианты заявок. Пожалуйста, попробуйте снова."
      },`
};

for (const lang of Object.keys(newTranslations)) {
  const marker = new RegExp('(' + lang + ':\\s*\\{[\\s\\S]*?dashboard:\\s*\\{)');
  if (!tsContent.includes('newApp: {')) {
    tsContent = tsContent.replace(marker, '$1\\n' + newTranslations[lang]);
  }
}

fs.writeFileSync(tsPath, tsContent);
console.log('Updated translations.ts');
